Repository Clean-Code-Team/Invaders, pull requests merged in 2023-10, with the labels that each got.

#16 rename : change some strings to uppercase to suit the font
  src/engine/DrawManager.java
Labels: 🛠️ refactoring

#15 Change Bullet Graphic
  .gitignore
  res/graphics
Labels: 📑 docs, 📍 feature

#18 feat: added countdown design and changed bullet graphics
  .gitignore
  res/graphics
  res/invader_1.png
  res/invader_2.png
  res/invader_3.png
  res/invader_4.png
  src/engine/DrawManager.java
  src/screen/GameScreen.java
Labels: 📑 docs, 🛠️ refactoring, 📍 feature

#19 refactor: delete png files and add drawEntity method
  res/invader_1.png
  res/invader_2.png
  res/invader_3.png
  res/invader_4.png
  src/engine/DrawManager.java
Labels: 🛠️ refactoring

#20 fix: edited .gitignore and settings.json
  .github/workflows/build-gradle-project.yml
  .gitignore
  .vscode/settings.json
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/engine/DrawManager.java
  test/scoreColorTest.java
Labels: 🐝 bug

#21 fix: add repository configuration code related to CI
  .github/workflows/build-gradle-project.yml
  .gitignore
  .idea/misc.xml
Labels: 📍 feature, ✅ test

#25 feat: added a slowly changing color effect
  src/engine/DrawManager.java
  test/slowlyChangingColorsTest.java
Labels: 📍 feature, ✅ test

#26 feat: add death effect blank skull
  res/graphics
  src/engine/DrawManager.java
  src/entity/EnemyShip.java
Labels: 📍 feature

#28 feat: create new Bullet `BulletY.java`
  res/graphics
  src/engine/DrawManager.java
  src/entity/BulletPool.java
  src/entity/BulletY.java
  src/entity/Entity.java
  src/entity/Ship.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
Labels: 📍 feature

#31 Sync main & feature/bulletY_7
  res/graphics
  src/engine/DrawManager.java
  src/entity/BulletPool.java
  src/entity/BulletY.java
  src/entity/Entity.java
  src/entity/Ship.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
Labels: 📍 feature

#33 bug: fix confilct related to BGM TEAM
  src/effect/ShipEffect.java
  src/entity/BulletPool.java
  src/entity/Ship.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
Labels: 🐝 bug

#34 bug: fix conflict related to BGM Team
  src/effect/ShipEffect.java
  src/entity/BulletPool.java
  src/entity/Ship.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
Labels: 🐝 bug

#36 feat: Destroy the ship at the end of the game
  src/screen/GameScreen.java
Labels: 📍 feature

#38 feat: Create game over pop-up
  src/engine/DrawManager.java
  src/screen/GameScreen.java
Labels: 📍 feature

#37 feat: background related improvements
  src/engine/Cooldown.java
  src/engine/DrawManager.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
Labels: 📍 feature

#40 feat:add design of items
  requirements/CleanCode.md
  res/graphics
  src/engine/DrawManager.java
Labels: 📍 feature

#41 feat: Add Stage Clear
  src/engine/DrawManager.java
  src/screen/GameScreen.java
Labels: 📍 feature

#43 feat: add new death effect
  res/graphics
  src/engine/DrawManager.java
  src/entity/EnemyShip.java
Labels: 📑 docs, 📍 feature

#45 Feature/ending scene 9
  res/graphics
  src/engine/DrawManager.java
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: 📍 feature

#46 feat: add moving ghosts
  res/graphics
  src/engine/DrawManager.java
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: 📍 feature

#48 docs: comment out unused packages
  src/entity/EnemyShipFormation.java
Labels: 🐝 bug

#47 docs: CleanCode.md update
  requirements/CleanCode.md
  src/entity/EnemyShipFormation.java
Labels: 🐝 bug, 📑 docs

#49 docs : add description about contdown design in CleanCode.md
  requirements/CleanCode.md
Labels: 📑 docs

#51 docs: modified CleanCode.md
  requirements/CleanCode.md
  src/engine/DrawManager.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
Labels: 📑 docs

#52 docs: request to review the final revision of CleanCode.md
  requirements/CleanCode.md
Labels: 📑 docs
